### ISSUE TITLE
nightly.sh should not override RELEASE_MICRO in env file

### ISSUE THREAD

**Issue by andy-js** [gdamore/illumos-core#166]
There is already a check in the nightly.sh file before setting RELEASE_DATE.  There should be a similar one for RELEASE_MICRO.

**Comment by gdamore** [comment]
@andy-js did you plan to submit a PR for this?

**Comment by andy-js** [comment]
I did not.  I can prepare a git-format patch though if you like.

**Comment by gdamore** [comment]
If you do, I’ll check it and integrate it assuming it doesn’t have any issues.  (And I’d give you feedback otherwise.)

	- Garrett
